### ISSUE TITLE
Unregister MCMChain

### ISSUE THREAD

**Issue by cossio** [TuringLang/MCMCChains.jl#77] opened 2019-04-02 15:59 UTC
It seems it is still possible to install an `MCMCChain` package via `pkg> add MCMCChain`.
This is confusing because now the package is named `MCMCChains` (with the `s` at the end), and installing `MCMCChain` (by accident or ignorance) gets you an older version and results in errors.

Is it possible to "unregister" `MCMCChain` so that only `MCMCChains` is listed?

**Comment by goedman** [comment] 2019-04-02 22:07
Unregister I think is not possible.  As it was renamed I don't think we can set an upper bound on it.

I wonder if the best solution is to create a __init__() in MCMCChain.jl with a clear @warn (or even stronger) about this issue. Would that have helped you?

**Comment by cossio** [comment] 2019-04-02 22:16
Yes, some indication that it is the wrong package would be helpful.

**Comment by cpfiffer** [comment] 2019-04-03 13:29
@goedman how do we go back to make a new release with an `@warn` message?

**Comment by goedman** [comment] 2019-04-03 13:47
Don't ask me these hard questions :-) ! I wanted to dig into that today. I think we also have another problem come next Monday when Attobot is being switched off. I think we need to add a Project.toml file to MCMCChains (and I think the same will be needed for all TuringLang packages).

After I wrote the reply I realized MCMCChain will likely not show up in the new Registry. Otherwise we might have to do some old-fashioned magic my manually registering MCMCChain and put an upper bound on Julia.

As you can see, some investigative work is needed here ...

**Comment by yebai** [comment] 2019-04-03 13:57
I think we can solve this following these steps:

- temporarily change the name of this repo back to `MCMCChain`
- create a branch from the last `MCMCChain` release and make it the temporary `master`
- tag a new release from the temporary `master`
- and wait for the `Attobot ` PR getting merged into `METADATA`

Once a release for `MCMCChain` is available in `METADATA`, we can change the repo's name to `MCMCChains` again, and restore the `master` branch from its backup. With a lot of hope, this will work ; )

**Comment by goedman** [comment] 2019-04-03 14:30
Yes, that might work, but renaming in combination with METADATA has always been tricky.

MCMCChains right now is not in the new Registry. If Julia switches over on Monday (and switch off Attobot in favor of the new Registrator) the problem of continuing to use `using MCMCChain` or `] add MCMCChain` is mitigated even further. Renaming it back to MCMCChain at this point might in fact create an entry for it in the General Registry.

Another (additional) option could be for TuringLang to use the pinning option for repositories on Github and use 1 of the 6 spots for MCMCChains and include a note that MCMCChain has been renamed.

**Comment by mkborregaard** [comment] 2019-04-03 14:54
I think that's preferable to spending a lot of energy updating MCMCChain. We're all going to be changing to a different registry soon anyway (GENERAL).

**Comment by mkborregaard** [comment] 2019-04-03 14:54
@cossio made the same comment on StatPlots. I honestly don't think this needs to be a big problem.

**Comment by cossio** [comment] 2019-04-03 19:33
Yeah, I thought this was a simple thing. Probably not worth it if it is that complicated. But as @mkborregaard suggested in `StatsPlots` (https://github.com/JuliaPlots/StatsPlots.jl/issues/225), maybe `MCMCChain` can be "unregistered" (I'm not sure if this is possible) in the future? 

Maybe this is something that should be discussed in the context of `Pkg` in general. I only found this: https://discourse.julialang.org/t/renaming-packages/10433.

**Comment by mkborregaard** [comment] 2019-04-03 20:34
Now there's https://discourse.julialang.org/t/switching-package-registration-systems-on-monday/22677 so maybe the problem is solving itself.

**Comment by goedman** [comment] 2019-04-03 21:11
Don't think so unfortunately. MCMCChains was transferred through the syncing with METADATA. But I suggest we wait until the transfer to the General registry is a few weeks behind us to see if something can and needs to be done.

**Closed** 2019-04-25 12:50 UTC

**Comment by DilumAluthge** [comment] 2026-02-06 00:53
Hi all, I know this issue is pretty old, but I wanted to follow-up with new developments.

In Julia 1.14 and later, Pkg.jl will have the ability to understand that a package is deprecated. You can see the dev build of the docs here: https://pkgdocs.julialang.org/dev/registries/#Deprecated-packages (once Julia 1.14 is out, it'll be available in the regular docs build: https://pkgdocs.julialang.org/v1/registries/#Deprecated-packages)

Based on the discussion in this issue, would it make sense to deprecate MCMCChain (singular) in favor of MCMCChains (plural)? I've opened a PR here: https://github.com/JuliaRegistries/General/pull/147712
