### ISSUE TITLE
ChainDataFrame slice ignores symbol key

### ISSUE THREAD

**Issue by phipsgabler** [TuringLang/MCMCChains.jl#244] opened 2020-10-11 09:22 UTC
I suppose the following is not intentional?

```julia
julia> e[Symbol("w[1]"), :]
ESS
  parameters     ess   r_hat
  ──────────  ──────  ──────
        w[1]  4.4639  1.0522
        w[2]  4.4639  1.0522
        z[1]     NaN     NaN
        z[2]     NaN     NaN
        z[3]     NaN     NaN
        z[4]     NaN     NaN
        z[5]     NaN     NaN
        z[6]     NaN     NaN
        z[7]     NaN     NaN
        z[8]     NaN     NaN
        z[9]     NaN     NaN
       z[10]     NaN     NaN
        μ[1]  4.9389  1.0134
        μ[2]  4.3662  1.0619


julia> e[Symbol("w[1]")]
ESS
  parameters     ess   r_hat
  ──────────  ──────  ──────
        w[1]  4.4639  1.0522
```

Looks like [this line][1] accidentially ignores the symbol key.

[1]: https://github.com/TuringLang/MCMCChains.jl/blob/fa6757ad3044abf1dc8f8cee3f0bd0a690899cf8/src/summarize.jl#L42

**Comment by devmotion** [comment] 2020-10-11 09:28
Yeah, looks like a bug. Can you submit a PR? :slightly_smiling_face:

**Comment by phipsgabler** [comment] 2020-10-11 15:55
I'm really sorry for being so lazy with PRs recently, but I try to keep the state of my package system frozen as much as possible until my thesis work is finished.  I can catch up on a lot of things once that's done.

**Comment by devmotion** [comment] 2020-10-11 16:26
I see, no worries :slightly_smiling_face: I'm busy right now but maybe I can put together a PR in the next days.

BTW in my experience, it is very convenient to have reproducible package environments for all important projects. In particular, this means I try to only pin packages to git commits but never to use packages (or custom fixes of packages) in `.julia/dev`. If something has to be fixed for my work but it takes too much time to wait until a PR to the package is merged by the maintainers, I fork the package and create a working branch there (still good to keep individual bug fixes in separate branches, so it's easy to submit PRs). Then it's fine to still do some package hacking in `.julia/dev` if needed, without causing any issues in my current projects :slightly_smiling_face:

**Comment by cpfiffer** [comment] 2020-10-11 18:09
I'll get a PR up for this one.

**Closed** 2020-10-11 20:01 UTC
