### ISSUE TITLE
Weird error for indexing chain with a scalar

### ISSUE THREAD

**Issue by phipsgabler** [TuringLang/MCMCChains.jl#190] opened 2020-03-03 16:05 UTC
That a does not really behave like an array of samples is surprising for the initiated, but OK.  I must admit that I still don't get how indexing is supposed to work.  But the following error message could be _much_ better, I think:

<details>
<summary>Details</summary>

```
julia> chain[:p][1]
Object of type Chains, with data of type 1×1×1 Array{Float64,3}

Iterations        = 1:1
Thinning interval = 1
Chains            = 1
Samples per chain = 1
parameters        = p

Error showing value of type Chains{Float64,Missing,NamedTuple{(:parameters,),Tuple{Array{String,1}}},NamedTuple{(:range, :model, :spl, :vi, :hashedsummary),Tuple{Random._GLOBAL_RNG,DynamicPPL.Model{var"##inner_function#433#6",NamedTuple{(:y,),Tuple{Array{Int64,1}}},DynamicPPL.ModelGen{(:y,),var"###coinflip#447",NamedTuple{(),Tuple{}}},Val{()}},DynamicPPL.Sampler{MH{()},Turing.Inference.MHState{DynamicPPL.VarInfo{NamedTuple{(:p,),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:p},Int64},Array{Beta{Float64},1},Array{DynamicPPL.VarName{:p},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64}}},DynamicPPL.VarInfo{NamedTuple{(:p,),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:p},Int64},Array{Beta{Float64},1},Array{DynamicPPL.VarName{:p},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},Base.RefValue{Tuple{UInt64,Array{ChainDataFrame,1}}}}}}:
ERROR: BoundsError: attempt to access 0-element Array{Any,1} at index [1]
Stacktrace:
 [1] getindex(::Array{Any,1}, ::Int64) at ./array.jl:744
 [2] #ess#203(::Bool, ::Array{Symbol,1}, ::Int64, ::Missing, ::typeof(ess), ::Chains{Float64,Missing,NamedTuple{(:parameters,),Tuple{Array{String,1}}},NamedTuple{(:range, :model, :spl, :vi, :hashedsummary),Tuple{Random._GLOBAL_RNG,DynamicPPL.Model{var"##inner_function#433#6",NamedTuple{(:y,),Tuple{Array{Int64,1}}},DynamicPPL.ModelGen{(:y,),var"###coinflip#447",NamedTuple{(),Tuple{}}},Val{()}},DynamicPPL.Sampler{MH{()},Turing.Inference.MHState{DynamicPPL.VarInfo{NamedTuple{(:p,),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:p},Int64},Array{Beta{Float64},1},Array{DynamicPPL.VarName{:p},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64}}},DynamicPPL.VarInfo{NamedTuple{(:p,),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:p},Int64},Array{Beta{Float64},1},Array{DynamicPPL.VarName{:p},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},Base.RefValue{Tuple{UInt64,Array{ChainDataFrame,1}}}}}}) at /home/philipp/.julia/packages/MCMCChains/YabhG/src/stats.jl:338
 [3] #ess at ./none:0 [inlined]
 [4] #summarystats#218(::Bool, ::Bool, ::Array{Symbol,1}, ::Symbol, ::Missing, ::Bool, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(summarystats), ::Chains{Float64,Missing,NamedTuple{(:parameters,),Tuple{Array{String,1}}},NamedTuple{(:range, :model, :spl, :vi, :hashedsummary),Tuple{Random._GLOBAL_RNG,DynamicPPL.Model{var"##inner_function#433#6",NamedTuple{(:y,),Tuple{Array{Int64,1}}},DynamicPPL.ModelGen{(:y,),var"###coinflip#447",NamedTuple{(),Tuple{}}},Val{()}},DynamicPPL.Sampler{MH{()},Turing.Inference.MHState{DynamicPPL.VarInfo{NamedTuple{(:p,),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:p},Int64},Array{Beta{Float64},1},Array{DynamicPPL.VarName{:p},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64}}},DynamicPPL.VarInfo{NamedTuple{(:p,),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:p},Int64},Array{Beta{Float64},1},Array{DynamicPPL.VarName{:p},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},Base.RefValue{Tuple{UInt64,Array{ChainDataFrame,1}}}}}}) at /home/philipp/.julia/packages/MCMCChains/YabhG/src/stats.jl:404
 [5] (::StatsBase.var"#kw##summarystats")(::NamedTuple{(:showall, :sections, :etype, :digits),Tuple{Bool,Array{Symbol,1},Symbol,Missing}}, ::typeof(summarystats), ::Chains{Float64,Missing,NamedTuple{(:parameters,),Tuple{Array{String,1}}},NamedTuple{(:range, :model, :spl, :vi, :hashedsummary),Tuple{Random._GLOBAL_RNG,DynamicPPL.Model{var"##inner_function#433#6",NamedTuple{(:y,),Tuple{Array{Int64,1}}},DynamicPPL.ModelGen{(:y,),var"###coinflip#447",NamedTuple{(),Tuple{}}},Val{()}},DynamicPPL.Sampler{MH{()},Turing.Inference.MHState{DynamicPPL.VarInfo{NamedTuple{(:p,),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:p},Int64},Array{Beta{Float64},1},Array{DynamicPPL.VarName{:p},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64}}},DynamicPPL.VarInfo{NamedTuple{(:p,),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:p},Int64},Array{Beta{Float64},1},Array{DynamicPPL.VarName{:p},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},Base.RefValue{Tuple{UInt64,Array{ChainDataFrame,1}}}}}}) at ./none:0
 [6] #describe#195(::Array{Float64,1}, ::Symbol, ::Bool, ::Array{Symbol,1}, ::Missing, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(describe), ::Base.TTY, ::Chains{Float64,Missing,NamedTuple{(:parameters,),Tuple{Array{String,1}}},NamedTuple{(:range, :model, :spl, :vi, :hashedsummary),Tuple{Random._GLOBAL_RNG,DynamicPPL.Model{var"##inner_function#433#6",NamedTuple{(:y,),Tuple{Array{Int64,1}}},DynamicPPL.ModelGen{(:y,),var"###coinflip#447",NamedTuple{(),Tuple{}}},Val{()}},DynamicPPL.Sampler{MH{()},Turing.Inference.MHState{DynamicPPL.VarInfo{NamedTuple{(:p,),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:p},Int64},Array{Beta{Float64},1},Array{DynamicPPL.VarName{:p},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64}}},DynamicPPL.VarInfo{NamedTuple{(:p,),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:p},Int64},Array{Beta{Float64},1},Array{DynamicPPL.VarName{:p},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},Base.RefValue{Tuple{UInt64,Array{ChainDataFrame,1}}}}}}) at /home/philipp/.julia/packages/MCMCChains/YabhG/src/stats.jl:164
 [7] describe(::Base.TTY, ::Chains{Float64,Missing,NamedTuple{(:parameters,),Tuple{Array{String,1}}},NamedTuple{(:range, :model, :spl, :vi, :hashedsummary),Tuple{Random._GLOBAL_RNG,DynamicPPL.Model{var"##inner_function#433#6",NamedTuple{(:y,),Tuple{Array{Int64,1}}},DynamicPPL.ModelGen{(:y,),var"###coinflip#447",NamedTuple{(),Tuple{}}},Val{()}},DynamicPPL.Sampler{MH{()},Turing.Inference.MHState{DynamicPPL.VarInfo{NamedTuple{(:p,),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:p},Int64},Array{Beta{Float64},1},Array{DynamicPPL.VarName{:p},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64}}},DynamicPPL.VarInfo{NamedTuple{(:p,),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:p},Int64},Array{Beta{Float64},1},Array{DynamicPPL.VarName{:p},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},Base.RefValue{Tuple{UInt64,Array{ChainDataFrame,1}}}}}}) at /home/philipp/.julia/packages/MCMCChains/YabhG/src/stats.jl:164
 [8] #describe#194(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(describe), ::Chains{Float64,Missing,NamedTuple{(:parameters,),Tuple{Array{String,1}}},NamedTuple{(:range, :model, :spl, :vi, :hashedsummary),Tuple{Random._GLOBAL_RNG,DynamicPPL.Model{var"##inner_function#433#6",NamedTuple{(:y,),Tuple{Array{Int64,1}}},DynamicPPL.ModelGen{(:y,),var"###coinflip#447",NamedTuple{(),Tuple{}}},Val{()}},DynamicPPL.Sampler{MH{()},Turing.Inference.MHState{DynamicPPL.VarInfo{NamedTuple{(:p,),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:p},Int64},Array{Beta{Float64},1},Array{DynamicPPL.VarName{:p},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64}}},DynamicPPL.VarInfo{NamedTuple{(:p,),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:p},Int64},Array{Beta{Float64},1},Array{DynamicPPL.VarName{:p},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},Base.RefValue{Tuple{UInt64,Array{ChainDataFrame,1}}}}}}) at /home/philipp/.julia/packages/MCMCChains/YabhG/src/stats.jl:136
 [9] describe at /home/philipp/.julia/packages/MCMCChains/YabhG/src/stats.jl:136 [inlined]
 [10] show(::IOContext{REPL.Terminals.TTYTerminal}, ::Chains{Float64,Missing,NamedTuple{(:parameters,),Tuple{Array{String,1}}},NamedTuple{(:range, :model, :spl, :vi, :hashedsummary),Tuple{Random._GLOBAL_RNG,DynamicPPL.Model{var"##inner_function#433#6",NamedTuple{(:y,),Tuple{Array{Int64,1}}},DynamicPPL.ModelGen{(:y,),var"###coinflip#447",NamedTuple{(),Tuple{}}},Val{()}},DynamicPPL.Sampler{MH{()},Turing.Inference.MHState{DynamicPPL.VarInfo{NamedTuple{(:p,),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:p},Int64},Array{Beta{Float64},1},Array{DynamicPPL.VarName{:p},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64}}},DynamicPPL.VarInfo{NamedTuple{(:p,),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:p},Int64},Array{Beta{Float64},1},Array{DynamicPPL.VarName{:p},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},Base.RefValue{Tuple{UInt64,Array{ChainDataFrame,1}}}}}}) at /home/philipp/.julia/packages/MCMCChains/YabhG/src/chains.jl:311
 [11] show(::IOContext{REPL.Terminals.TTYTerminal}, ::MIME{Symbol("text/plain")}, ::Chains{Float64,Missing,NamedTuple{(:parameters,),Tuple{Array{String,1}}},NamedTuple{(:range, :model, :spl, :vi, :hashedsummary),Tuple{Random._GLOBAL_RNG,DynamicPPL.Model{var"##inner_function#433#6",NamedTuple{(:y,),Tuple{Array{Int64,1}}},DynamicPPL.ModelGen{(:y,),var"###coinflip#447",NamedTuple{(),Tuple{}}},Val{()}},DynamicPPL.Sampler{MH{()},Turing.Inference.MHState{DynamicPPL.VarInfo{NamedTuple{(:p,),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:p},Int64},Array{Beta{Float64},1},Array{DynamicPPL.VarName{:p},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64}}},DynamicPPL.VarInfo{NamedTuple{(:p,),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:p},Int64},Array{Beta{Float64},1},Array{DynamicPPL.VarName{:p},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},Base.RefValue{Tuple{UInt64,Array{ChainDataFrame,1}}}}}}) at ./multimedia.jl:47
 [12] display(::REPL.REPLDisplay, ::MIME{Symbol("text/plain")}, ::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/REPL/src/REPL.jl:132
 [13] display(::REPL.REPLDisplay, ::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/REPL/src/REPL.jl:136
 [14] display(::Any) at ./multimedia.jl:323
 [15] #invokelatest#1 at ./essentials.jl:709 [inlined]
 [16] invokelatest at ./essentials.jl:708 [inlined]
 [17] print_response(::IO, ::Any, ::Bool, ::Bool, ::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/REPL/src/REPL.jl:156
 [18] print_response(::REPL.AbstractREPL, ::Any, ::Bool, ::Bool) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/REPL/src/REPL.jl:141
 [19] (::REPL.var"#do_respond#38"{Bool,REPL.var"#48#57"{REPL.LineEditREPL,REPL.REPLHistoryProvider},REPL.LineEditREPL,REPL.LineEdit.Prompt})(::Any, ::Any, ::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/REPL/src/REPL.jl:719
 [20] #invokelatest#1 at ./essentials.jl:709 [inlined]
 [21] invokelatest at ./essentials.jl:708 [inlined]
 [22] run_interface(::REPL.Terminals.TextTerminal, ::REPL.LineEdit.ModalInterface, ::REPL.LineEdit.MIState) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/REPL/src/LineEdit.jl:2306
 [23] run_frontend(::REPL.LineEditREPL, ::REPL.REPLBackendRef) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/REPL/src/REPL.jl:1045
 [24] run_repl(::REPL.AbstractREPL, ::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/REPL/src/REPL.jl:201
 [25] (::Base.var"#770#772"{Bool,Bool,Bool,Bool})(::Module) at ./client.jl:382
 [26] #invokelatest#1 at ./essentials.jl:709 [inlined]
 [27] invokelatest at ./essentials.jl:708 [inlined]
 [28] run_main_repl(::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at ./client.jl:366
 [29] exec_options(::Base.JLOptions) at ./client.jl:304
 [30] _start() at ./client.jl:460
```

</details>

This at first made me wonder why my supposedly 1000 samples were stored an empty chain...

Alternatively (better?), make this return just a "scalar" sample, without fancy wrapping.

**Comment by devmotion** [comment] 2020-03-03 16:17
I agree, IMO the indexing is surprising and inconsistent at times. The issue here is a duplicate of https://github.com/TuringLang/MCMCChains.jl/issues/137 and fixed, e.g., by https://github.com/TuringLang/MCMCChains.jl/pull/156. Unfortunately I haven't found the time yet to finish up that PR.

**Comment by devmotion** [comment] 2020-04-28 21:33
On the `dev` branch this does not error anymore. The behaviour changed significantly (not on the master branch though yet) as explained in https://github.com/TuringLang/MCMCChains.jl/pull/197#issuecomment-605429030. Now `chain[:p]` returns just a two-dimensional `AxisArray` object of samples for `:p`, of which the first dimension corresponds to the iterations and the second one to the chains:
```julia
julia> using MCMCChains

julia> chain = Chains(rand(100, 4, 5), [:a, :b, :c, :p]);

julia> chain[:p]
2-dimensional AxisArray{Float64,2,...} with axes:       
    :iter, 1:1:100                                      
    :chain, 1:5
And data, a 100×5 Array{Float64,2}:
 0.941945     0.749002    0.770661   0.8924     0.608436
 0.0719007    0.536491    0.726919   0.646775   0.869203
 0.135036     0.484901    0.318927   0.545704   0.532132
 0.584907     0.0307205   0.547664   0.326701   0.854289
 0.657731     0.125024    0.666162   0.875255   0.769294
...
```
Hence `chain[:p][1]` just returns the first entry of this matrix:
```julia
julia> chain[:p][1]
0.9419452619467878
```
All samples of `:p` in the first chain can be obtained by
```julia
julia> chain[:p][:, 1]
1-dimensional AxisArray{Float64,1,...} with axes:
    :iter, 1:1:100
And data, a 100-element Array{Float64,1}:
 0.9419452619467878
 0.07190067180030923
 0.1350357253240484
 0.5849068882889958
 0.6577311317965637
 0.4180743692665958
 0.3985048604471886
 0.3807698491807905
...
```
although it is more efficient to just index the chain in the following way:
```julia
julia> chain[:, :p, 1]
1-dimensional AxisArray{Float64,1,...} with axes:
    :iter, 1:1:100
And data, a 100-element Array{Float64,1}:
 0.9419452619467878
 0.07190067180030923
 0.1350357253240484
 0.5849068882889958
 0.6577311317965637
 0.4180743692665958
 0.3985048604471886
 0.3807698491807905
 ...
```
Similarly, if you just want the first sample of `:p` in the first chain you could do
```julia
julia> chain[1, :p, 1]
0.9419452619467878
```

If the indexing operation does not reduce any dimension (i.e., no scalar indexing along any of the dimensions), then you'll get a `Chains` object. For instance (probably a bit artificially):
```julia
julia> chain[:, [:p], 1:1]
Chains MCMC chain (100×1×1 Array{Float64,3}):

Iterations        = 1:100
Thinning interval = 1
Chains            = 1
Samples per chain = 100
parameters        = p

Summary Statistics
  parameters      mean       std   naive_se      mcse        ess      rhat  
      Symbol   Float64   Float64    Float64   Missing    Float64   Float64  
                                                                            
           p    0.4237    0.2883     0.0288   missing   119.9563    0.9986  

Quantiles
  parameters      2.5%     25.0%     50.0%     75.0%     97.5%  
      Symbol   Float64   Float64   Float64   Float64   Float64  
                                                                
           p    0.0091    0.1689    0.3854    0.6607    0.9376
```

**Comment by devmotion** [comment] 2020-05-21 15:27
The dev branch is merged into master now.

**Closed by devmotion** 2020-05-21 15:27 UTC
