### ISSUE TITLE
autocorplot is broken

### ISSUE THREAD

**Issue by itsdfish** [TuringLang/MCMCChains.jl#187] opened 2020-02-27 00:06 UTC
Hi-

I noticed that `autocorplot` no longer works. Here is a MWE:

```
using MCMCChains, StatsPlots 

val = rand(500,5, 2)
chn = Chains(val, ["a", "b", "c", "d", "e"])
autocorplot(chn)

```
Error:

```
Error showing value of type Plots.Plot{Plots.GRBackend}:
ERROR: BoundsError: attempt to access 28-element Array{Float64,1} at index [1:29]
Stacktrace:
 [1] throw_boundserror(::Array{Float64,1}, ::Tuple{UnitRange{Int64}}) at ./abstractarray.jl:538
 [2] checkbounds at ./abstractarray.jl:503 [inlined]
 [3] getindex(::Array{Float64,1}, ::UnitRange{Int64}) at ./array.jl:750
 [4] gr_display(::Plots.Subplot{Plots.GRBackend}, ::Measures.Length{:mm,Float64}, ::Measures.Length{:mm,Float64}, ::Array{Float64,1}) at /home/dfish/.julia/packages/Plots/CFRKM/src/backends/gr.jl:1590
 [5] gr_display(::Plots.Plot{Plots.GRBackend}, ::String) at /home/dfish/.julia/packages/Plots/CFRKM/src/backends/gr.jl:706
 [6] gr_display at /home/dfish/.julia/packages/Plots/CFRKM/src/backends/gr.jl:664 [inlined]
 [7] _display(::Plots.Plot{Plots.GRBackend}) at /home/dfish/.julia/packages/Plots/CFRKM/src/backends/gr.jl:1941
 [8] display(::Plots.PlotsDisplay, ::Plots.Plot{Plots.GRBackend}) at /home/dfish/.julia/packages/Plots/CFRKM/src/output.jl:152
 [9] display(::Any) at ./multimedia.jl:323
 [10] #invokelatest#1 at ./essentials.jl:709 [inlined]
 [11] invokelatest at ./essentials.jl:708 [inlined]
 [12] print_response(::IO, ::Any, ::Bool, ::Bool, ::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/REPL/src/REPL.jl:156
 [13] print_response(::REPL.AbstractREPL, ::Any, ::Bool, ::Bool) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/REPL/src/REPL.jl:141
 [14] (::REPL.var"#do_respond#38"{Bool,REPL.var"#48#57"{REPL.LineEditREPL,REPL.REPLHistoryProvider},REPL.LineEditREPL,REPL.LineEdit.Prompt})(::Any, ::Any, ::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/REPL/src/REPL.jl:719
 [15] #invokelatest#1 at ./essentials.jl:709 [inlined]
 [16] invokelatest at ./essentials.jl:708 [inlined]
 [17] run_interface(::REPL.Terminals.TextTerminal, ::REPL.LineEdit.ModalInterface, ::REPL.LineEdit.MIState) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/REPL/src/LineEdit.jl:2306
 [18] run_frontend(::REPL.LineEditREPL, ::REPL.REPLBackendRef) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/REPL/src/REPL.jl:1045
 [19] run_repl(::REPL.AbstractREPL, ::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/REPL/src/REPL.jl:201
 [20] (::Base.var"#770#772"{Bool,Bool,Bool,Bool})(::Module) at ./client.jl:382
 [21] #invokelatest#1 at ./essentials.jl:709 [inlined]
 [22] invokelatest at ./essentials.jl:708 [inlined]
 [23] run_main_repl(::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at ./client.jl:366
 [24] exec_options(::Base.JLOptions) at ./client.jl:304
 [25] _start() at ./client.jl:460
```
Version:

```
(v1.3) pkg> st MCMCChains
    Status `~/.julia/environments/v1.3/Project.toml`
  [31c24e10] Distributions v0.22.4
  [c7f686f2] MCMCChains v3.0.2
  [2913bbd2] StatsBase v0.32.1
```

**Comment by devmotion** [comment] 2020-02-27 05:57
Hej! Does it work if you specify `maxlag`? I guess we should just upperbound `maxlag` in https://github.com/TuringLang/MCMCChains.jl/blob/master/src/plot.jl#L61.

**Comment by itsdfish** [comment] 2020-02-27 08:04
Having a default would be convenient. I think the previous default was 30. 

Unfortunately, entering an explicit value for maxlag did not work:

```
 autocorplot(chn, maxlag=30)
Error showing value of type Plots.Plot{Plots.GRBackend}:
ERROR: BoundsError: attempt to access 31-element Array{Float64,1} at index [1:32]
Stacktrace:
 [1] throw_boundserror(::Array{Float64,1}, ::Tuple{UnitRange{Int64}}) at ./abstractarray.jl:538
 [2] checkbounds at ./abstractarray.jl:503 [inlined]
 [3] getindex(::Array{Float64,1}, ::UnitRange{Int64}) at ./array.jl:750
 [4] gr_display(::Plots.Subplot{Plots.GRBackend}, ::Measures.Length{:mm,Float64}, ::Measures.Length{:mm,Float64}, ::Array{Float64,1}) at /home/dfish/.julia/packages/Plots/CFRKM/src/backends/gr.jl:1590
 [5] gr_display(::Plots.Plot{Plots.GRBackend}, ::String) at /home/dfish/.julia/packages/Plots/CFRKM/src/backends/gr.jl:706
 [6] gr_display at /home/dfish/.julia/packages/Plots/CFRKM/src/backends/gr.jl:664 [inlined]
 [7] _display(::Plots.Plot{Plots.GRBackend}) at /home/dfish/.julia/packages/Plots/CFRKM/src/backends/gr.jl:1941
 [8] display(::Plots.PlotsDisplay, ::Plots.Plot{Plots.GRBackend}) at /home/dfish/.julia/packages/Plots/CFRKM/src/output.jl:152
 [9] display(::Any) at ./multimedia.jl:323
 [10] #invokelatest#1 at ./essentials.jl:709 [inlined]
 [11] invokelatest at ./essentials.jl:708 [inlined]
 [12] print_response(::IO, ::Any, ::Bool, ::Bool, ::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/REPL/src/REPL.jl:156
 [13] print_response(::REPL.AbstractREPL, ::Any, ::Bool, ::Bool) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/REPL/src/REPL.jl:141
 [14] (::REPL.var"#do_respond#38"{Bool,REPL.var"#48#57"{REPL.LineEditREPL,REPL.REPLHistoryProvider},REPL.LineEditREPL,REPL.LineEdit.Prompt})(::Any, ::Any, ::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/REPL/src/REPL.jl:719
 [15] #invokelatest#1 at ./essentials.jl:709 [inlined]
 [16] invokelatest at ./essentials.jl:708 [inlined]
 [17] run_interface(::REPL.Terminals.TextTerminal, ::REPL.LineEdit.ModalInterface, ::REPL.LineEdit.MIState) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/REPL/src/LineEdit.jl:2306
 [18] run_frontend(::REPL.LineEditREPL, ::REPL.REPLBackendRef) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/REPL/src/REPL.jl:1045
 [19] run_repl(::REPL.AbstractREPL, ::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/REPL/src/REPL.jl:201
 [20] (::Base.var"#770#772"{Bool,Bool,Bool,Bool})(::Module) at ./client.jl:382
 [21] #invokelatest#1 at ./essentials.jl:709 [inlined]
 [22] invokelatest at ./essentials.jl:708 [inlined]
 [23] run_main_repl(::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at ./client.jl:366
 [24] exec_options(::Base.JLOptions) at ./client.jl:304
 [25] _start() at ./client.jl:460

```

**Comment by devmotion** [comment] 2020-02-27 08:10
Yes, I noticed the issue is caused by some other problem. When `autocor` some lines above creates a `ChainDataFrame` in which the first column are `parameters` and the others are the lags, and when it is converted to array `ac` we end up with a matrix with `lags + 1` columns where the first column is just undefined (it's defined in summarize.jl). Of course, when we try to plot then the autocorrelation values versus the lags there's a mismatch, resulting in the error. I'm currently checking what's the most reasonable fix for it and how it was handled before the update, i.e., if we should rather subset the matrix or handle the conversion differently (IMO returning a matrix with a column of random floating point numbers doesn't seem reasonable and expected).

**Comment by devmotion** [comment] 2020-02-27 10:27
Before https://github.com/TuringLang/MCMCChains.jl/commit/a07520735cb5bb70b7a775045f3e3722c9c39641#diff-86d9ffeffc1c0b02dd396a8a83f3a138, the first column was just dropped, so I implemented the same behaviour in https://github.com/TuringLang/MCMCChains.jl/pull/188.

**Comment by itsdfish** [comment] 2020-02-27 11:56
Thanks for the quick turnaround!

**Comment by cpfiffer** [comment] 2020-02-27 13:33
MCMCChains 3.0.3 should fix this when [this goes through](https://github.com/JuliaRegistries/General/pull/10134). Thanks, @devmotion!

**Comment by itsdfish** [comment] 2020-03-02 21:05
Now I receive an intermittent error. traceplot seems to work consistently in such cases. For some reason, the underlying arrays are `Real`

```
chain[:s].value.data
1000×1×4 Array{Real,3}:
```
Here is the error message:
```
 pcs = plot(chain[:s], seriestype=(:autocorplot))
ERROR: MethodError: no method matching fptype(::Type{Real})
Closest candidates are:
  fptype(::Type{Complex{Float32}}) at /home/dfish/.julia/packages/StatsBase/Q9jSr/src/common.jl:27
  fptype(::Type{Complex{Float64}}) at /home/dfish/.julia/packages/StatsBase/Q9jSr/src/common.jl:28
  fptype(::Type{T}) where T<:Union{Bool, Float32, Int16, Int8, UInt16, UInt8} at /home/dfish/.julia/packages/StatsBase/Q9jSr/src/common.jl:25
  ...
Stacktrace:
 [1] #autocor#89(::Bool, ::typeof(autocor), ::Array{Real,1}, ::Array{Int64,1}) at /home/dfish/.julia/packages/StatsBase/Q9jSr/src/signalcorr.jl:186
 [2] (::StatsBase.var"#kw##autocor")(::NamedTuple{(:demean,),Tuple{Bool}}, ::typeof(autocor), ::Array{Real,1}, ::Array{Int64,1}) at ./none:0
 [3] (::MCMCChains.var"#191#192"{Bool,Int64})(::Array{Real,1}) at /home/dfish/.julia/packages/MCMCChains/4j7Of/src/stats.jl:31
 [4] (::MCMCChains.var"#100#109"{MCMCChains.var"#191#192"{Bool,Int64},Int64})(::Int64) at ./none:0
 [5] iterate at ./generator.jl:47 [inlined]
 [6] collect(::Base.Generator{UnitRange{Int64},MCMCChains.var"#100#109"{MCMCChains.var"#191#192"{Bool,Int64},Int64}}) at ./array.jl:622
 [7] (::MCMCChains.var"#99#108"{Int64})(::MCMCChains.var"#191#192"{Bool,Int64}) at ./none:0
 [8] iterate at ./generator.jl:47 [inlined]
 [9] collect(::Base.Generator{NTuple{31,MCMCChains.var"#191#192"{Bool,Int64}},MCMCChains.var"#99#108"{Int64}}) at ./array.jl:622
 [10] (::MCMCChains.var"#98#107"{NTuple{31,MCMCChains.var"#191#192"{Bool,Int64}}})(::Int64) at ./none:0
 [11] iterate at ./generator.jl:47 [inlined]
 [12] collect(::Base.Generator{UnitRange{Int64},MCMCChains.var"#98#107"{NTuple{31,MCMCChains.var"#191#192"{Bool,Int64}}}}) at ./array.jl:622
 [13] #summarize#95(::Array{Symbol,1}, ::Array{Symbol,1}, ::Bool, ::Bool, ::String, ::Nothing, ::Int64, ::Bool, ::typeof(MCMCChains.summarize), ::Chains{Real,Missing,NamedTuple{(:parameters,),Tuple{Array{String,1}}},NamedTuple{(),Tuple{}}}, ::MCMCChains.var"#191#192"{Bool,Int64}, ::Vararg{MCMCChains.var"#191#192"{Bool,Int64},N} where N) at /home/dfish/.julia/packages/MCMCChains/4j7Of/src/summarize.jl:252
 [14] (::MCMCChains.var"#kw##summarize")(::NamedTuple{(:func_names, :showall, :sections, :append_chains, :name, :digits),Tuple{Array{Symbol,1},Bool,Array{Symbol,1},Bool,String,Int64}}, ::typeof(MCMCChains.summarize), ::Chains{Real,Missing,NamedTuple{(:parameters,),Tuple{Array{String,1}}},NamedTuple{(),Tuple{}}}, ::Function, ::Vararg{Function,N} where N) at ./none:0
 [15] #autocor#190(::UnitRange{Int64}, ::Bool, ::Bool, ::Bool, ::Bool, ::Array{Symbol,1}, ::Int64, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(autocor), ::Chains{Real,Missing,NamedTuple{(:parameters,),Tuple{Array{String,1}}},NamedTuple{(),Tuple{}}}) at /home/dfish/.julia/packages/MCMCChains/4j7Of/src/stats.jl:33
 [16] (::StatsBase.var"#kw##autocor")(::NamedTuple{(:lags, :showall),Tuple{UnitRange{Int64},Bool}}, ::typeof(autocor), ::Chains{Real,Missing,NamedTuple{(:parameters,),Tuple{Array{String,1}}},NamedTuple{(),Tuple{}}}) at ./none:0
 [17] macro expansion at /home/dfish/.julia/packages/MCMCChains/4j7Of/src/plot.jl:62 [inlined]
 [18] apply_recipe(::Dict{Symbol,Any}, ::Chains{Real,Missing,NamedTuple{(:parameters,),Tuple{Array{String,1}}},NamedTuple{(),Tuple{}}}, ::Int64) at /home/dfish/.julia/packages/RecipesBase/G4s6f/src/RecipesBase.jl:279
 [19] _process_userrecipes(::Plots.Plot{Plots.PyPlotBackend}, ::Dict{Symbol,Any}, ::Tuple{Chains{Real,Missing,NamedTuple{(:parameters,),Tuple{Array{String,1}}},NamedTuple{(),Tuple{}}}}) at /home/dfish/.julia/packages/Plots/B2J6j/src/pipeline.jl:85
 [20] _plot!(::Plots.Plot{Plots.PyPlotBackend}, ::Dict{Symbol,Any}, ::Tuple{Chains{Real,Missing,NamedTuple{(:parameters,),Tuple{Array{String,1}}},NamedTuple{(),Tuple{}}}}) at /home/dfish/.julia/packages/Plots/B2J6j/src/plot.jl:178
 [21] #plot#138(::Base.Iterators.Pairs{Symbol,Symbol,Tuple{Symbol},NamedTuple{(:seriestype,),Tuple{Symbol}}}, ::typeof(plot), ::Chains{Real,Missing,NamedTuple{(:parameters,),Tuple{Array{String,1}}},NamedTuple{(),Tuple{}}}) at /home/dfish/.julia/packages/Plots/B2J6j/src/plot.jl:57
 [22] (::RecipesBase.var"#kw##plot")(::NamedTuple{(:seriestype,),Tuple{Symbol}}, ::typeof(plot), ::Chains{Real,Missing,NamedTuple{(:parameters,),Tuple{Array{String,1}}},NamedTuple{(),Tuple{}}}) at ./none:0
 [23] top-level scope at none:0
```
Any ideas?

**Comment by devmotion** [comment] 2020-03-02 21:13
Have you sampled the chain with Turing? And does the example in the first comment still work?

**Comment by itsdfish** [comment] 2020-03-02 21:22
Yeah. It appears that Turing is part of the problem because the example above works. Here is a MWE:


```
using Turing, Random, MCMCChains, StatsPlots

Random.seed!(1101)

@model model(y) = begin
    μ ~ Normal(0, 1)
    s ~ Truncated(Cauchy(0, 1), 0, Inf)
    for i in 1:length(y)
        y[i] ~ Normal(μ, s)
    end 
end

y = rand(Normal(0, 1), 10) 

chain = sample(model(y), NUTS(1000, .65), 2000)
plot(chain, seriestype=(:autocorplot))
```

**Comment by itsdfish** [comment] 2020-03-02 21:22
P.S. For some reason, that model runs really slow.

**Comment by devmotion** [comment] 2020-03-02 21:32
Hmm, Turing's type problem sounds a bit similar to https://github.com/TuringLang/Turing.jl/issues/1115#issuecomment-586962520. Regarding the performance issues, have you tried to use `MvNormal` instead of the loop of normal distributions?

**Comment by itsdfish** [comment] 2020-03-02 21:55
No. I just mocked up a MWE and noticed it was very slow. In the past, such a model would have ran in about 0.2 seconds. Now it runs in about 2-4 minutes, depending on the run. 

MvNormal seems to suffer from the same problem:

```
using Turing, Random, MCMCChains, StatsPlots

Random.seed!(1101)

@model model(y) = begin
    μ ~ Normal(0, 1)
    s ~ Truncated(Cauchy(0, 1), 0, Inf)
    # for i in 1:length(y)
        y ~ MvNormal(fill(μ, length(y)), s)
    # end 
end

y = rand(Normal(0, 1), 10) 

chain = sample(model(y), NUTS(1000, .85),  2000)
```

```
Results:
Sampling 100%|███████████████████████████████| Time: 0:02:08
  iteration:                     2000
  n_steps:                       1
  is_accept:                     true
  acceptance_rate:               1.0
  log_density:                   -15.892608717534614
  hamiltonian_energy:            16.691212614618912
  hamiltonian_energy_error:      -0.15525124257628775
  max_hamiltonian_energy_error:  -0.15525124257628775
  tree_depth:                    1
  numerical_error:               false
  step_size:                     0.6316712851464531
  nom_step_size:                 0.6316712851464531
  mass_matrix:                   DiagEuclideanMetric([0.07798499653850086, 0.054 ...])

```

**Comment by devmotion** [comment] 2020-03-02 22:29
It runs in ~0.2 seconds for me if I replace the deprecated `Truncated` with `truncated`. Can you check if the performance issues are resolved for you as well if you use `s ~ truncated(Cauchy(0, 1), 0, Inf)`?

**Comment by itsdfish** [comment] 2020-03-02 23:03
Yeah. That fixed it. Thank you.

By the way, why do both exist? It's a bit confusing.

**Comment by devmotion** [comment] 2020-03-02 23:19
`truncated` enables the implementation of more efficient distributions whereas `Truncated` is just a generic distribution type. As the [docs](https://juliastats.org/Distributions.jl/stable/truncate/#Distributions.Truncated) mention, `truncated`
> Builds the most appropriate distribution for the type of d, the fallback is constructing a Truncated wrapper.

**Comment by cpfiffer** [comment] 2020-03-02 23:52
Yeah, this is a problem where Turing doesn't enforce exporting a common denominator type (like `Float64`) and instead just lets everything be it's own thing. I believe at one point Turing enforced the export of a `Float64` array when sampling was done, and that MCMCChains enforced this when chains were created, but over the months both these checks have vanished (perhaps for the better?).

The way I see it, we've got a couple options:

1. Let the internal matrix be whatever type it wants -- this might be good if you've got bools, integers, and floating points together, which you might expect to be generated by a modern probabilistic model. Then, we just check whether each column (variable) is a relevant type before a summary function is called -- autocorrelation doesn't make much sense for integers, so we could just return `missing` in these cases. This is kind of a band-aid approach that might work but at a pretty hefty typing cost.
2. Force the internal matrix to be `Float64`. Also not really a good idea since I think we should care when things are integers or booleans, but all of this stuff would just go back to normal.

Any preferences?

**Comment by cpfiffer** [comment] 2020-03-02 23:54
We can also just convert everything to floats just ahead of numerical functions like `autocor` but leave the internal matrix as `Real`. Same issues as noted above.

**Comment by itsdfish** [comment] 2020-03-07 08:35
Would it be possible to reopen this issue?

**Comment by mkborregaard** [comment] 2020-03-07 08:58
Hey, is this an issue with the plotting code, or earlier in the pipeline? It's a bit hard to read from the issue.

**Comment by devmotion** [comment] 2020-03-07 09:21
IMO it's an issue with StatsBase. As discussed, ideally Turing should return a concretely typed chain and not Array{<:Real} but the error occurs in https://github.com/JuliaStats/StatsBase.jl/blob/65351de819ca64941cb81c047e4b77157446f7c5/src/signalcorr.jl#L186 since `fptype(Real)` is not defined. Since
```julia
julia> float(Real)
Float64
```
IMO StatsBase should just define `fptype(::Type{Real}) = Float64` as well (BTW I'm wondering if one should get rid of `fptype` in StatsBase since it doesn't work with custom (e.g., dual) number types either - or maybe one should just define the fallback `fptype(::Type{T}) where T = float(T)`?).

**Comment by devmotion** [comment] 2020-03-07 09:28
There's even an issue with exactly this discussion: https://github.com/JuliaStats/StatsBase.jl/issues/459

**Comment by cpfiffer** [comment] 2020-03-07 17:33
What's the best glue fix here? We can

1. Open a PR at StatsBase to add `fptype(::Type{Real}) = Float64`
2. Make Turing export an array `Array{Float64,3}`
3. Work really hard and replace `fptype` with `float`

I'm inclined towards 2 for the moment, with the eye that MCMCChains should internally be more resilient to this kind of thing.

**Comment by devmotion** [comment] 2020-03-07 19:57
I've already submitted a PR to StatsBase that fixes the problem (should be linked in this issue).

**Comment by devmotion** [comment] 2020-03-08 19:30
Regarding 2: Maybe it would make more sense to export `StructArray`s in Turing? I'm still not convinced that one should promote integer-valued samples to floating point numbers just because some other samples are floating-point valued.

**Comment by cpfiffer** [comment] 2020-03-09 02:49
> Regarding 2: Maybe it would make more sense to export `StructArray`s in Turing? I'm still not convinced that one should promote integer-valued samples to floating point numbers just because some other samples are floating-point valued.

Yeah, I agree. I think though we shouldn't just export (by default) a `StructArray`, but an `AbstractChains` object that is full-featured like `MCMCChains`. One with a backend that utilizes `StructArrays` and maintains type information. 

We could maybe try to just swap out the `AxisArrays` backend to `StructArrays`, or make a different package to test it out.

**Comment by devmotion** [comment] 2020-03-27 17:46
I close this issue since it is fixed with MCMCChains 3.0.8 and StatsBase 0.33. Your example in https://github.com/TuringLang/MCMCChains.jl/issues/187#issuecomment-593628945 produces now
![autocorplot2](https://user-images.githubusercontent.com/26102/77784649-2860f880-705b-11ea-8b69-07a2b1fb2bad.png)
(Apparently one shouldn't use unicode characters with GR :smile: )

**Closed by devmotion** 2020-03-27 17:46 UTC

**Comment by cpfiffer** [comment] 2020-03-27 22:23
As a side note, the fix to the unicode plotting issue is here: https://github.com/JuliaPlots/Plots.jl/issues/791#issuecomment-481550142

**Comment by devmotion** [comment] 2020-03-27 22:25
Ah perfect, thanks :+1:
