### ISSUE TITLE
Cor no longer works

### ISSUE THREAD

**Issue by itsdfish** [TuringLang/MCMCChains.jl#189] opened 2020-03-02 19:14 UTC
I found that cor no longer works. Here is a MWE:

```
using MCMCChains, StatsPlots 
import MCMCChains: cor 

val = rand(500,5, 2)
chn = Chains(val, ["a", "b", "c", "d", "e"])
cor(chn)
```
Error:
```
UndefVarError: DataFrame not defined
#cor#193(::Bool, ::Bool, ::Array{Symbol,1}, ::Int64, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(cor), ::Chains{Float64,Missing,NamedTuple{(:parameters,),Tuple{Array{Any,1}}},NamedTuple{(),Tuple{}}}) at stats.jl:59
cor(::Chains{Float64,Missing,NamedTuple{(:parameters,),Tuple{Array{Any,1}}},NamedTuple{(),Tuple{}}}) at stats.jl:59
top-level scope at untitled-84e45c9bd5bfc567b46b3d7282fc1695:5
```

```
(v1.3) pkg> st MCMCChains
    Status `~/.julia/environments/v1.3/Project.toml`
  [31c24e10] Distributions v0.22.5
  [c7f686f2] MCMCChains v3.0.3
  [2913bbd2] StatsBase v0.32.1
```

**Comment by devmotion** [comment] 2020-03-02 20:22
The problem is that `DataFrame` is still used in `src/stats.jl` even though DataFrames is only an optional dependency. You should be able to work around the issue by explicitly loading DataFrames, but of course this should be fixed properly.

**Comment by itsdfish** [comment] 2020-03-02 20:53
Thanks. Unfortunately, loading DataFrames failed as a workaround. It produced the same error message.

**Comment by devmotion** [comment] 2020-03-02 21:19
Ah, I forgot, one should run `@eval MCMCChains begin using DataFrames end`. However, unfortunately that throws a different error since the constructor of `ChainDataFrame` was changed.

**Comment by devmotion** [comment] 2020-03-23 14:36
This was fixed by https://github.com/TuringLang/MCMCChains.jl/pull/194.

**Closed by devmotion** 2020-03-23 14:36 UTC
